services:
  api:
    hostname: "prowler-api"
    build:
      context: .
      dockerfile: api/Dockerfile
      target: dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.devel
      - PYTHONPATH=/home/prowler
    env_file:
      - path: .env
        required: false
    ports:
      - "9090:${DJANGO_PORT:-8080}"
    volumes:
      - ./api/src/backend:/home/prowler/backend
      - ./api/pyproject.toml:/home/prowler/pyproject.toml
      - ./api/docker-entrypoint.sh:/home/prowler/docker-entrypoint.sh
      - ./prowler:/home/prowler/prowler
      - ./_data/api:/home/prowler/.config/prowler-api
      - output:/tmp/prowler_api_output
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    entrypoint:
      - "/home/prowler/docker-entrypoint.sh"
      - "dev"

  postgres:
    image: postgres:16.3-alpine3.20
    hostname: "postgres-db"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - path: .env
        required: false
    ports:
      - "127.0.0.1:5433:${POSTGRES_PORT:-5432}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_ADMIN_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:7-alpine3.19
    hostname: "valkey"
    volumes:
      - ./_data/valkey:/data
    env_file:
      - path: .env
        required: false
    ports:
      - "127.0.0.1:6380:6379"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'valkey-cli ping'"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.devel
      - PYTHONPATH=/home/prowler
    env_file:
      - path: .env
        required: false
    volumes:
      - ./api/docker-entrypoint.sh:/home/prowler/docker-entrypoint.sh
      - ./prowler:/home/prowler/prowler
      - ./_data/api:/home/prowler/.config/prowler-api
      - output:/tmp/prowler_api_output
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    entrypoint:
      - "/home/prowler/docker-entrypoint.sh"
      - "worker"

  worker-beat:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: dev
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.devel
      - PYTHONPATH=/home/prowler
    env_file:
      - path: .env
        required: false
    volumes:
      - ./api/docker-entrypoint.sh:/home/prowler/docker-entrypoint.sh
      - ./prowler:/home/prowler/prowler
      - ./_data/api:/home/prowler/.config/prowler-api
      - output:/tmp/prowler_api_output
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    entrypoint:
      - "/home/prowler/docker-entrypoint.sh"
      - "beat"

volumes:
  postgres-data:
    driver: local
  output:
    driver: local
